src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Hours__c</fullName>
        <inlineHelpText>Total number of Hours that are Completed. Hours with other status values are not included.</inlineHelpText>
        <label>Volunteer Hours</label>
        <summarizedField>Volunteer_Hours__c.Hours_Worked__c</summarizedField>
        <summaryFilterItems>
            <field>Volunteer_Hours__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryForeignKey>Volunteer_Hours__c.Contact__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

src/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Clock_In_Time__c</fullName>
        <description>The time stamp a volunteer begins their work</description>
        <label>Clock In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Clock_Out_Time__c</fullName>
        <description>The time stamp a volunteer ends their work</description>
        <label>Clock Out Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Sign Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Note__c</fullName>
        <inlineHelpText>Text information from the system scheduler.</inlineHelpText>
        <label>System Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volunteer Shift</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Volunteer_Shift__c.Volunteer_Job__c</field>
                <operation>equals</operation>
                <valueField>$Source.Volunteer_Job__c</valueField>
            </filterItems>
            <infoMessage>You can only pick a Shift which belongs to the current Job.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Volunteer_Shift__c</referenceTo>
        <relationshipLabel>Volunteer Hours</relationshipLabel>
        <relationshipName>Volunteer_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Volunteer_Job__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Volunteer Jobs</relationshipLabel>
        <relationshipName>Volunteer_Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Display_on_Website__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this field if this Volunteer Job should be included in the Available Volunteer Jobs Sites page.</inlineHelpText>
        <label>Display on Website</label>
        <type>Checkbox</type>
    </fields>
    <label>Volunteer Job</label>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Volunteer_Shift__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <inlineHelpText>How many hours long is the shift?</inlineHelpText>
        <label>Duration (Hours)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <label>Start Date &amp; Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>System_Note__c</fullName>
        <inlineHelpText>Text information from the system scheduler.</inlineHelpText>
        <label>System Note</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <referenceTo>Volunteer_Job__c</referenceTo>
        <relationshipLabel>Volunteer Shifts</relationshipLabel>
        <relationshipName>Volunteer_Job_Slots</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Volunteer Shift</label>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <nameField>
        <label>ShiftID</label>
        <type>AutoNumber</type>
        <displayFormat>Shift-{00000}</displayFormat>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/VOL_CTRL_VolunteersClockOutHours_TEST.cls
@IsTest
public class VOL_CTRL_VolunteersClockOutHours_TEST {
	
    //==================== TEST METHOD(s) ======================================
    public static testmethod void TestClockout() {
        Campaign cmp = new Campaign(recordtypeid=VOL_SharedCode.recordtypeIdVolunteersCampaign, name='Test Job Campaign', IsActive=true);
        insert cmp;
        Volunteer_Job__c job = new Volunteer_Job__c(name='Job1', campaign__c=cmp.Id, Display_on_Website__c=true);
        insert job;
        Volunteer_Shift__c shift = new Volunteer_Shift__c(Volunteer_Job__c=job.Id, Duration__c=1, Start_Date_Time__c=System.now());
        insert shift;
        Contact con1 = new Contact();
            con1.FirstName = 'TestFirstName1';
            con1.LastName = 'TestLastName1';
            con1.Email = 'foovolunteer@bar.com';
        insert con1;
        Contact con2 = new Contact();
            con2.FirstName = 'TestFirstName2';
            con2.LastName = 'TestLastName2';
            con2.Email = 'foovolunteer2@bar.com';
        insert con2;
        Contact con3 = new Contact();
            con3.FirstName = 'TestFirstName3';
            con3.LastName = 'TestLastName3';
            con3.Email = 'foovolunteer3@bar.com';
        insert con3;
        
        Volunteer_Hours__c hr1 = new Volunteer_Hours__c(
        	Contact__c=con1.id,
            Volunteer_Job__c = job.Id,
            Volunteer_Shift__c = shift.Id,
            Clock_In_Time__c = system.now()-0.5/24/60,
            Start_Date__c = System.Today(),
            End_Date__c = System.Today(),
            Status__c = 'In Progress'
        );
        insert hr1;
        Volunteer_Hours__c hr2 = new Volunteer_Hours__c(
        	Contact__c=con2.id,
            Volunteer_Job__c = job.Id,
            Volunteer_Shift__c = shift.Id,
            Start_Date__c = System.Today(),
            End_Date__c = System.Today(),
            Status__c = 'Confirmed'
        );
        insert hr2;
        Volunteer_Hours__c hr3 = new Volunteer_Hours__c(
        	Contact__c=con3.id,
            Volunteer_Job__c = job.Id,
            Volunteer_Shift__c = shift.Id,
            Clock_In_Time__c = system.now()-0.5/24/60,
            Start_Date__c = System.Today(),
            End_Date__c = System.Today(),
            Status__c = 'In Progress'
        );
        insert hr3;
        
        List<Volunteer_Hours__c> selHrs = [select id,name,
                                           Status__c,
                                           Clock_In_Time__c,
                                           Clock_Out_Time__c,
                                           End_Date__c,
                                           Hours_Worked__c,
                                           System_Note__c from Volunteer_Hours__c where Status__c='In Progress'];
        
        ApexPages.StandardSetController ctrl = new ApexPages.StandardSetController(selHrs);
        VOL_CTRL_VolunteersClockOutHours extension = new VOL_CTRL_VolunteersClockOutHours(ctrl);  
       
        ctrl.setSelected(selHrs);
        system.assert(ctrl.getSelected()!=null);
        extension.clockOut();
        
        List<Volunteer_Hours__c> hrs = [select id,name from Volunteer_Hours__c where Status__c='Completed'];
        system.assertEquals(hrs.size(),2);
        
    }
    
}