src/objects/Volunteer_Hours__c.object
<CustomObject>
    <fields>
        <fullName>Clock_In_Time__c</fullName>
        <description>The time stamp a volunteer begins their work</description>
        <label>Clock In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Clock_Out_Time__c</fullName>
        <description>The time stamp a volunteer ends their work</description>
        <label>Clock Out Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours_Worked__c</fullName>
        <label>Hours Worked</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No-Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Sign Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Note__c</fullName>
        <inlineHelpText>Text information from the system scheduler.</inlineHelpText>
        <label>System Note</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

src/classes/VOL_CTRL_VolunteersClockOutHours.cls
public class VOL_CTRL_VolunteersClockOutHours {

    ApexPages.StandardSetController setCon;
    public Volunteer_Hours__c hr {get;set;}
    public String cancelLabel {get;set;}

    public VOL_CTRL_VolunteersClockOutHours(ApexPages.StandardSetController controller) {
        setCon = controller;
        cancelLabel = 'Cancel';
    }

    public pageReference clockOut() {

        for ( Volunteer_Hours__c hr : (Volunteer_Hours__c[])setCon.getSelected()) {
            hr.Status__c = 'Completed';
            hr.Clock_Out_Time__c = system.now();
            hr.End_Date__c = system.today();
            hr.Hours_Worked__c = decimal.valueOf(hr.Clock_Out_Time__c.getTime() - hr.Clock_In_Time__c.getTime())/3600000;
            hr.System_Note__c = 'Logged Out By '+ UserInfo.getName() +' using mass Clock Out';
            update hr;
        }
        cancelLabel = 'Done';
        return null;
    }
}